[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "{{ cookiecutter.module_name }}"
authors = [
    # TODO configure authors
    # { name = "Jane Smith", email = "jane.smith@example.com" },
    # { name = "John Doe", email = "john.doe@example.com" },
]
description = ""
readme = "README.md"
requires-python = "~={{ cookiecutter.__python_version }}.0"
dependencies = [
    # TODO configure install dependencies
]
dynamic = ["version"]

[dependency-groups]
dev = [
    "ipykernel~={{ cookiecutter.__ipykernel_version }}",
    "pre-commit~={{ cookiecutter.__pre_commit_version }}",
{%- if cookiecutter.use_pytest %}
    "pytest~={{ cookiecutter.__pytest_version }}",
{%- endif %}
{%- if cookiecutter.use_ruff_format or cookiecutter.use_ruff_lint %}
    "ruff=={{ cookiecutter.__ruff_version }}",
{%- endif %}
]

[tool.hatch.version]
path = "src/{{ cookiecutter.module_name }}/__init__.py"
{%- if cookiecutter.use_pytest %}

[tool.pytest]
testpaths = ["tests"]
addopts = ["--import-mode=importlib"]
strict = true
{%- endif %}
{%- if cookiecutter.use_ruff_format or cookiecutter.use_ruff_lint %}

[tool.ruff]
target-version = "py{{ cookiecutter.__python_version.replace(".", "") }}"
line-length = 88
{%- if cookiecutter.use_ruff_lint %}

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "I", "RUF1", "UP", "W"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
{%- endif %}
{%- endif %}
